[project]
# Change this to customize the name of your app shown in the UI and the tab title
name = "VeriFact"
# Enable telemetry
enable_telemetry = false

[features]
# Set to true to enable multi-modal messages
multi_modal = true
# Set to true to enable this to save user settings
user_settings = true
# Set to true to enable steps recording
steps = true

[UI]
# Name of the app and chatbot
name = "VeriFact"
# Description of the app and chatbot. This is used for HTML tags.
description = "AI-powered fact-checking platform to verify claims with evidence and verdicts"
# Large size content are by default collapsed for a cleaner UI
default_collapse_content = true
# The default value for the expand messages settings.
default_expand_messages = false
# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "full"
# Link to your github repo. This will add a github button in the UI's header.
github = "https://github.com/yourusername/verifact"

# Custom action buttons that appear in the UI header
[[UI.actions]]
name = "view_history"
label = "View History"
description = "View your past fact-checks"
icon = "history"

[UI.theme]
# Change the color palette of the app
font_family = "Inter, sans-serif"
layout = "wide"

[UI.theme.light]
primary = "#2563EB"
background = "#F8FAFC"
paper = "#FFFFFF"

[UI.theme.dark]
primary = "#3B82F6"
background = "#0F172A"
paper = "#1E293B"

[dataPersistence]
# Change this to customize where the chat history is stored locally
file_path = "./.chatlit/chat_history.json"

[dataPersistence.database]
# Change this to use a different database for chat history persistence
# postgresql+asyncpg://user:password@localhost:5432/database
# connection_string = "your_connection_string"
# table_name = "chat_history"

[features.audio]
enabled = false

[features.video]
enabled = false 