version: "3.8"

services:
  # VeriFact UI service (Chainlit)
  verifact-ui:
    build:
      context: .
      dockerfile: Dockerfile
    command: ui
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./configs:/app/configs
    env_file:
      - .env
    environment:
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=8501
      - SUPABASE_DB_URL=postgresql://postgres:postgres@verifact-db:5432/postgres
    depends_on:
      - verifact-db
    restart: unless-stopped

  # VeriFact API service (FastAPI)
  verifact-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./configs:/app/configs
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - SUPABASE_DB_URL=postgresql://postgres:postgres@verifact-db:5432/postgres
    depends_on:
      - verifact-db
    restart: unless-stopped

  # PostgreSQL database with pgvector extension
  verifact-db:
    image: pgvector/pgvector:pg14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

volumes:
  db-data:
