[project]
name = "verifact"
version = "0.1.0"
description = "A mutli-agent system to verify claims in text"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.5.5",
    "fastapi>=0.115.12",
    "ipykernel>=6.29.5",
    "openai-agents>=0.0.15",
    "uvicorn>=0.34.2",
]
